<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_burger_dashboard</name>
   <tag></tag>
   <elementGuidId>a4f77d96-6d95-478d-b39d-28327943d296</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.dashboard-menus.ml-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/main/div/div[1]/div[1]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>06a0acf2-dd0f-4c29-97bd-6f2a7184e9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn dashboard-menus ml-2</value>
      <webElementGuid>c3b1972e-f708-46c9-9c8d-25261081e066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;sidebar min&quot;]/div[@class=&quot;org-header&quot;]/div[@class=&quot;d-flex flex-row align-items-center justify-content-center&quot;]/a[@class=&quot;btn dashboard-menus ml-2&quot;]</value>
      <webElementGuid>6f282638-a032-4147-b6fe-5ce113be6c87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div/div/div/a</value>
      <webElementGuid>c661cdeb-cdfd-405e-b11b-7675962d39f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BigBang Inc'])[1]/following::a[1]</value>
      <webElementGuid>3954ee61-a2fc-4be5-9a76-6c2fe3c42eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Task'])[1]/preceding::a[6]</value>
      <webElementGuid>1750746e-5317-4e92-9675-542e42290d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comment'])[1]/preceding::a[7]</value>
      <webElementGuid>196297d4-d20b-4d19-bdd9-fb4e7f7105f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>605bd657-bf02-4a20-a13d-34678d3a7625</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
