<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SearchTeamMembers</name>
   <tag></tag>
   <elementGuidId>1fc4ba1f-3081-4cf2-b92a-732690a496b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/main/div/div[2]/div[2]/div/div/div[2]/div/div[3]/div/div/div/form/div[3]/div[4]/div/div/div[1]/div/div[1]/div[1]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
