<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_update</name>
   <tag></tag>
   <elementGuidId>1cc1e8a0-79ae-452e-9f07-705c375b0926</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/main/div/div[2]/div[2]/div/div/div[2]/div/div[3]/div/div/div/form/div[4]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
