<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_clients</name>
   <tag></tag>
   <elementGuidId>213d5449-297c-4e49-b999-bc7b323c8882</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.d-flex.left-icon-item.flex-row.align-items-center.px-2.py-2.client-icon > p.nav-item-desc.ml-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/main/div/div[1]/div[2]/ul/li[2]/a/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>1eff1bc2-5a87-4bad-9bb9-03b1f970b131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-item-desc ml-3</value>
      <webElementGuid>5515780d-399d-4105-8e75-ac790576937a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clients</value>
      <webElementGuid>2ee59deb-765e-466d-939b-053cceb31c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-links&quot;)/ul[@class=&quot;link-list&quot;]/li[@class=&quot;&quot;]/a[@class=&quot;link-sidebar&quot;]/div[@class=&quot;d-flex left-icon-item flex-row align-items-center px-2 py-2 client-icon&quot;]/p[@class=&quot;nav-item-desc ml-3&quot;]</value>
      <webElementGuid>113a377c-cfcb-4619-9a53-53c45d20a9d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-links']/ul/li[2]/a/div/p</value>
      <webElementGuid>0c8b9340-e0df-4d90-8335-3e47c335218f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BigBang Inc'])[1]/following::p[2]</value>
      <webElementGuid>322a4ccc-2d2e-4805-8b0f-5f9c2c94de4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Task'])[1]/preceding::p[3]</value>
      <webElementGuid>76ddc5fa-de86-48ac-b11e-7826cb89d729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comment'])[1]/preceding::p[3]</value>
      <webElementGuid>9ea56a33-9525-48cd-be72-2b803b956b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Clients']/parent::*</value>
      <webElementGuid>d6f0a8e4-ac34-41ed-b5c3-91fcbd3a152a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div/p</value>
      <webElementGuid>cb14f91c-932c-4c1b-b8f3-f46e46743b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Clients' or . = 'Clients')]</value>
      <webElementGuid>56668461-2587-454d-8f1a-bd40c21e60bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
