<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AllClients</name>
   <tag></tag>
   <elementGuidId>dee233db-6ea9-405c-ab19-4e9cde41f13c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#c-select-new</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id=&quot;c-select-new&quot;]
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e4c34f30-3eae-4d58-a1e4-0a8611f229f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c-select-new</value>
      <webElementGuid>2c6cebb6-0466-42be-9ac3-cd03030529d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9cff74f9-c172-4a81-a91b-d69b6ab6f5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>56311098-e4c1-4c7b-8f85-496b7ee56be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>72606136-e276-46ca-a4b9-07b5c7c66ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-select-new position-relative flex-grow-1 w-100 d-block not-selectable d-flex align-items-center</value>
      <webElementGuid>23b9c3a1-1220-4722-bac1-833d3c89f7f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          All clients on this organization
         </value>
      <webElementGuid>ac6cb405-0d18-409b-a4bd-1d16c39ca4b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c-select-new&quot;)</value>
      <webElementGuid>ba415cfc-ddf8-4e39-a776-b0ac82e5f222</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='c-select-new']</value>
      <webElementGuid>18ac2f20-3d2b-4754-a2d9-0abb5ddd3882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c-select-new-vueor5s4']/div[2]</value>
      <webElementGuid>1e82dddf-b1e7-4b9d-abc1-17c33a407b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto-assign sponsored employees'])[1]/following::div[3]</value>
      <webElementGuid>22b54fe8-7121-44ce-83fc-cd85ef1dfc79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable Auto-Assign for Sponsored Employees'])[1]/following::div[4]</value>
      <webElementGuid>4b9ffdfe-44a5-4401-9b4f-b27d5f40f508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto-assign disabled'])[1]/preceding::div[2]</value>
      <webElementGuid>b307f009-a42a-478f-8211-1faf3962b4b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]</value>
      <webElementGuid>9d5e19a0-9fe3-4e3e-a037-f31e38b49338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'c-select-new' and (text() = '
          All clients on this organization
         ' or . = '
          All clients on this organization
         ')]</value>
      <webElementGuid>f24846e7-1eb7-40e5-a65e-368c65584adc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
