<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SelectClient</name>
   <tag></tag>
   <elementGuidId>91e3a15b-135b-4087-bbd9-e059dde0629e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/main/div/div[2]/div[2]/div/div/div[2]/div/div[3]/div/div/div/form/div[1]/div/div[3]/div/div[3]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
