<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Launch Legacy Profile</name>
   <tag></tag>
   <elementGuidId>b7e8d8dd-fe3a-4b2f-898c-26989590a5b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='banner-launch-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#banner-launch-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d73e9ebe-383d-43b1-b41b-22287f4cf4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/dashboard/clients/3/legacy_profile</value>
      <webElementGuid>2fc5845d-2f64-4f17-80a2-9af36fa86108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>banner-launch-btn</value>
      <webElementGuid>53c4bdde-a974-4b2c-81f5-7f9d7b29920b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded bg-blue-1 text-white</value>
      <webElementGuid>3eb886e7-f394-4788-bbf6-e1bd56da69a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Launch Legacy Profile</value>
      <webElementGuid>6a195b73-359f-40b1-a9b1-6d93bae053c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;banner-launch-btn&quot;)</value>
      <webElementGuid>f7d838f6-5583-4138-88f3-8c0693c8f1f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='banner-launch-btn']</value>
      <webElementGuid>1a922804-cb24-4c2a-b86d-03deb6619bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='banner-old-profile']/div[2]/a</value>
      <webElementGuid>cf8c4c61-02ed-49de-bb74-d1a7ea75b53b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Launch Legacy Profile')]</value>
      <webElementGuid>bf566db8-9195-4af5-848c-d0e46bc9525e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New client profile is now live as the current UI. You can still access the legacy client profile.'])[1]/following::a[1]</value>
      <webElementGuid>af16bc44-b92b-49da-97c0-38cf229bccbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comment'])[1]/following::a[3]</value>
      <webElementGuid>cdfe3b53-1737-4870-aadd-69cdb027e10a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MG'])[1]/preceding::a[1]</value>
      <webElementGuid>29d58463-25e1-4dad-a299-b62ed5926bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#3'])[1]/preceding::a[1]</value>
      <webElementGuid>3cda8aba-ee85-47cd-99b2-a111797b5029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Launch Legacy Profile']/parent::*</value>
      <webElementGuid>6d609dfd-ad9e-4d77-a5a0-1376b33432dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/dashboard/clients/3/legacy_profile')]</value>
      <webElementGuid>88c4444a-216f-4867-b256-394dc3796d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>efe543c0-5eb9-4a6d-a139-8b23ae71feeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/dashboard/clients/3/legacy_profile' and @id = 'banner-launch-btn' and (text() = 'Launch Legacy Profile' or . = 'Launch Legacy Profile')]</value>
      <webElementGuid>5906509b-2ee1-40c6-9c09-5f9cd8e74612</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
