<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Delete</name>
   <tag></tag>
   <elementGuidId>916a7cac-cd09-4f00-b8c3-1056e19598a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='right-section']/div[2]/div[2]/div[5]/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-danger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2eddec89-bd4f-4b85-a2c3-91fbab7264be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>e31c93c8-0f84-4ec9-a674-bcc840ad9433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-confirm</name>
      <type>Main</type>
      <value>Are you sure you want to delete this client?</value>
      <webElementGuid>0e832f1d-80fb-4b56-9516-0a3bbb99e81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-remote</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d8d75f74-c11e-49d4-982d-d1bb79243b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>8a0f5d1d-653a-4c82-ada3-7e90f80b3041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-method</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>bc3a6db5-2f9b-49ff-8e93-bc491cf8bdf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/clients/3</value>
      <webElementGuid>e430e223-fc38-4b4a-9c01-54489b7535d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>3635996e-d473-4fe0-9d91-1b9dda190bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;right-section&quot;)/div[@class=&quot;d-flex flex-row&quot;]/div[@class=&quot;info-panel order-2 flex-column flex-fill ml-auto border-left d-none d-md-flex&quot;]/div[@class=&quot;center&quot;]/div[1]/div[@class=&quot;p-3 border-top d-flex flex-column&quot;]/a[@class=&quot;btn btn-danger&quot;]</value>
      <webElementGuid>269765a5-480d-4285-892f-6e59bc687cef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='right-section']/div[2]/div[2]/div[5]/div/div[2]/a</value>
      <webElementGuid>85537813-f19a-4c8d-9b44-f671de5bbef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Delete')]</value>
      <webElementGuid>061440b0-79aa-43b3-b7aa-8e13911838a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending'])[1]/following::a[1]</value>
      <webElementGuid>1dbe7e3c-3b00-451e-9b56-15b118ea7ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document is being processed, check progress on process log!'])[1]/preceding::a[1]</value>
      <webElementGuid>a9ed1534-c52c-42ec-b49c-b8062f567a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/clients/3')])[12]</value>
      <webElementGuid>f1d40df6-28a1-4c1e-8a2a-efa373d0ede3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/a</value>
      <webElementGuid>b01ff01e-2154-4d3d-90cb-a82b74773c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/clients/3' and (text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>df607b6a-a3c6-4a07-8815-d8be94f89f5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
