<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_Comment</name>
   <tag></tag>
   <elementGuidId>84b90b9c-0416-4e0a-954a-1f2dee517e4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//b[@id='flash_notice']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flash_notice</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>430a2f2c-207c-4bcc-9033-b885150a340c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flash_notice</value>
      <webElementGuid>479a1849-e944-468b-8958-01b3d36c3fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Comment is successfully created.</value>
      <webElementGuid>096102f0-1bbb-4e4b-86bd-68e385727101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flash_notice&quot;)</value>
      <webElementGuid>73f00ff8-662c-4bc4-8b02-5a3ac7a208b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//b[@id='flash_notice']</value>
      <webElementGuid>ecf39b75-ca68-4a26-91f0-162e6830351e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='notify']/b</value>
      <webElementGuid>9052c1f5-e393-45cf-9aa2-5ace74b52416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reminders In Next 30 Days'])[1]/following::b[1]</value>
      <webElementGuid>dbba6442-c4c5-4112-bf42-82165801919b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No upcoming reminders.'])[1]/following::b[1]</value>
      <webElementGuid>5ce40abb-aa20-41b6-a6a1-033cc1010623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document is being processed, check progress on process log!'])[1]/preceding::b[1]</value>
      <webElementGuid>f5e6a200-6db4-4418-9693-75e25cd7b6b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'flash_notice', '&quot;', ')')])[1]/preceding::b[3]</value>
      <webElementGuid>823b42c7-99ff-4338-9741-89e3a89fc0f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Comment is successfully created.']/parent::*</value>
      <webElementGuid>eb677e88-d8a4-4cad-b152-2bedd3692b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/b</value>
      <webElementGuid>15623f7f-2b4e-4841-a1e8-95743ef20801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[@id = 'flash_notice' and (text() = 'Comment is successfully created.' or . = 'Comment is successfully created.')]</value>
      <webElementGuid>70206ca6-2ffe-47af-9b66-c2dc170d808e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
