<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Txt_condition</name>
   <tag></tag>
   <elementGuidId>21728bcc-a3c7-444a-90fc-1f547a5370f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='new_comment']/div/div/trix-editor</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>trix-editor.trix-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>trix-editor</value>
      <webElementGuid>cdc5d45a-d080-4cac-8ef5-8933f88b3ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>input</name>
      <type>Main</type>
      <value>comment_body</value>
      <webElementGuid>655a005f-69a6-42ad-a471-e58c13e1ca16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>trix-content</value>
      <webElementGuid>0f13a8f1-ce73-43cf-803f-498abd63a10f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>a834e3e3-ecac-4836-b915-6094108c5ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>trix-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8443e24d-f8fe-4a0f-8244-b9c7bdd74f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>toolbar</name>
      <type>Main</type>
      <value>trix-toolbar-1</value>
      <webElementGuid>3b0fa3c7-c04a-4717-b0fc-0e4e5aa2c25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new_comment&quot;)/div[@class=&quot;form-group trix_editor required comment_body&quot;]/div[@class=&quot;trix-editor-wrapper&quot;]/trix-editor[@class=&quot;trix-content&quot;]</value>
      <webElementGuid>5b7416f7-1243-4a47-9e33-d3d1628edc38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_comment']/div/div/trix-editor</value>
      <webElementGuid>5d79de7b-c8fc-4ba4-850f-280fa2069545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//trix-editor</value>
      <webElementGuid>151710f1-ac2a-4c54-8777-c50c1b0b9637</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
