<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_description</name>
   <tag></tag>
   <elementGuidId>73f986f4-e33c-4566-b1a1-60c748fe7590</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='task_description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#task_description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ed3ff3dc-652e-49c3-baee-cfed18442b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text optional</value>
      <webElementGuid>8e891810-ca6b-4f2f-a569-d5d376f3cf2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Description (optional)</value>
      <webElementGuid>e09db0b8-ee21-4e64-be99-10484802fa5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>task[description]</value>
      <webElementGuid>7ff7ad3a-2269-4847-95d2-b99c8992275d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>task_description</value>
      <webElementGuid>af2da428-78d6-4f2b-ac6a-a7f87d803098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task_description&quot;)</value>
      <webElementGuid>1ea1f90d-9e45-41e7-908e-dc6693ca5af5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='task_description']</value>
      <webElementGuid>2335fe09-5035-46d4-9f71-159961aa14f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_task']/div[2]/textarea</value>
      <webElementGuid>4f3b2d01-80cd-4113-b107-8856c8c834dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>ab7917da-7d40-4895-a536-0d24aa8bdf68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Description (optional)' and @name = 'task[description]' and @id = 'task_description']</value>
      <webElementGuid>0b85b7dd-34bc-4e21-bc6c-0284cc40c2ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
